import jsPDF from "jspdf";
import autoTable from "jspdf-autotable";
import type { ReadyRecordData } from "./types";
import {
  formatCurrency,
  maskSIN,
  maskCardNumber,
  totalCreditCardDebt,
  totalLineOfCreditDebt,
  totalBankBalances,
  totalRealEstateValue,
  totalMortgageBalance,
  totalMonthlyIncome,
  totalMonthlyExpenses,
  totalAssets,
  totalDebts,
  netWorth,
  monthlyNet,
  parseCurrency,
} from "./calculations";

const PAGE_MARGIN = 20;
const HEADER_COLOR: [number, number, number] = [85, 122, 91]; // sage-600

/** Map dropdown values to readable labels for PDF output */
const ACCOUNT_TYPE_LABELS: Record<string, string> = {
  chequing: "Chequing",
  savings: "Savings",
  rrsp: "RRSP",
  "spousal-rrsp": "Spousal RRSP",
  tfsa: "TFSA",
  rrif: "RRIF",
  "spousal-rrif": "Spousal RRIF",
  lif: "LIF",
  lrif: "LRIF",
  lira: "LIRA",
  gic: "GIC",
  "mutual-fund": "Mutual Fund",
  stocks: "Stocks / Brokerage",
  resp: "RESP",
  rdsp: "RDSP",
  other: "Other",
};

const INCOME_TYPE_LABELS: Record<string, string> = {
  cpp: "CPP",
  "cpp-disability": "CPP Disability",
  oas: "OAS",
  gis: "GIS",
  allowance: "Allowance / Survivor",
  dbpp: "Employer Pension (DBPP)",
  dcpp: "Employer Pension (DCPP)",
  rrif: "RRIF Withdrawal",
  lif: "LIF Withdrawal",
  lrif: "LRIF Withdrawal",
  annuity: "Annuity",
  investment: "Investment Income",
  rental: "Rental Income",
  employment: "Employment",
  "self-employment": "Self-Employment",
  "workers-comp": "Workers' Comp (WSIB/WCB)",
  veterans: "Veterans Affairs",
  "private-disability": "Private Disability",
  trust: "Trust Income",
  support: "Spousal/Child Support",
  other: "Other",
};

/** Format an ISO date string (yyyy-mm-dd) as a readable date */
function formatDate(isoDate: string): string {
  if (!isoDate) return "";
  const parts = isoDate.split("-");
  if (parts.length !== 3) return isoDate;
  const date = new Date(
    parseInt(parts[0]),
    parseInt(parts[1]) - 1,
    parseInt(parts[2])
  );
  if (isNaN(date.getTime())) return isoDate;
  return date.toLocaleDateString("en-CA", {
    year: "numeric",
    month: "long",
    day: "numeric",
  });
}

/** Check if Important Contacts has any data at all */
function hasContactsData(ic: ReadyRecordData["importantContacts"]): boolean {
  return Object.values(ic).some((v) => v.trim() !== "");
}

export function generatePDF(data: ReadyRecordData): void {
  const doc = new jsPDF("p", "mm", "letter");
  const pageWidth = doc.internal.pageSize.getWidth();
  let y = PAGE_MARGIN;

  const name = data.personalInfo.fullLegalName || "ReadyRecord Document";
  const dateStr = new Date().toLocaleDateString("en-CA", {
    year: "numeric",
    month: "long",
    day: "numeric",
  });

  function addFooter(pageNum: number) {
    const totalPages = doc.getNumberOfPages();
    doc.setFontSize(8);
    doc.setTextColor(150);
    doc.text(
      `Generated by ReadyRecord.ca on ${dateStr}`,
      PAGE_MARGIN,
      doc.internal.pageSize.getHeight() - 10
    );
    doc.text(
      `Page ${pageNum} of ${totalPages}`,
      pageWidth - PAGE_MARGIN,
      doc.internal.pageSize.getHeight() - 10,
      { align: "right" }
    );
  }

  function checkNewPage(needed: number): void {
    if (y + needed > doc.internal.pageSize.getHeight() - 25) {
      doc.addPage();
      y = PAGE_MARGIN;
    }
  }

  function sectionHeader(title: string): void {
    checkNewPage(20);
    doc.setFontSize(16);
    doc.setTextColor(...HEADER_COLOR);
    doc.setFont("helvetica", "bold");
    doc.text(title, PAGE_MARGIN, y);
    y += 4;
    doc.setDrawColor(...HEADER_COLOR);
    doc.setLineWidth(0.5);
    doc.line(PAGE_MARGIN, y, pageWidth - PAGE_MARGIN, y);
    y += 8;
    doc.setTextColor(30);
    doc.setFont("helvetica", "normal");
  }

  function labelValue(label: string, value: string, indent = 0): void {
    if (!value) return;
    checkNewPage(8);
    doc.setFontSize(10);
    doc.setFont("helvetica", "bold");
    doc.text(label + ":", PAGE_MARGIN + indent, y);
    doc.setFont("helvetica", "normal");
    doc.text(value, PAGE_MARGIN + indent + 55, y);
    y += 6;
  }

  // ============ COVER / SUMMARY PAGE ============
  doc.setFontSize(28);
  doc.setTextColor(...HEADER_COLOR);
  doc.setFont("helvetica", "bold");
  doc.text("ReadyRecord", pageWidth / 2, 40, { align: "center" });

  doc.setFontSize(14);
  doc.setTextColor(80);
  doc.setFont("helvetica", "normal");
  doc.text("Important Information Document", pageWidth / 2, 50, {
    align: "center",
  });

  doc.setFontSize(18);
  doc.setTextColor(30);
  doc.setFont("helvetica", "bold");
  doc.text(name, pageWidth / 2, 68, { align: "center" });

  doc.setFontSize(11);
  doc.setFont("helvetica", "normal");
  doc.setTextColor(100);
  doc.text(`Generated: ${dateStr}`, pageWidth / 2, 78, { align: "center" });

  // Summary table
  y = 95;
  doc.setFontSize(14);
  doc.setTextColor(...HEADER_COLOR);
  doc.setFont("helvetica", "bold");
  doc.text("Financial Summary", PAGE_MARGIN, y);
  y += 10;

  autoTable(doc, {
    startY: y,
    margin: { left: PAGE_MARGIN, right: PAGE_MARGIN },
    head: [["Category", "Amount"]],
    body: [
      ["Total Monthly Income", formatCurrency(totalMonthlyIncome(data))],
      ["Total Monthly Expenses", formatCurrency(totalMonthlyExpenses(data))],
      ["Monthly Net", formatCurrency(monthlyNet(data))],
      ["", ""],
      ["Total Assets", formatCurrency(totalAssets(data))],
      ["Total Debts", formatCurrency(totalDebts(data))],
      ["Estimated Net Worth", formatCurrency(netWorth(data))],
    ],
    headStyles: {
      fillColor: HEADER_COLOR,
      fontSize: 11,
    },
    bodyStyles: { fontSize: 10 },
    alternateRowStyles: { fillColor: [245, 247, 244] },
    theme: "grid",
  });

  // ============ SECTION 1: PERSONAL INFO ============
  doc.addPage();
  y = PAGE_MARGIN;
  sectionHeader("1. Personal Information");

  const pi = data.personalInfo;
  labelValue("Full Legal Name", pi.fullLegalName);
  labelValue("Address", pi.address);
  labelValue("Date of Birth", formatDate(pi.dateOfBirth));
  labelValue("Place of Birth", pi.placeOfBirth);
  labelValue("SIN", maskSIN(pi.sin));
  labelValue("Driver's License", pi.driversLicense);
  labelValue("Mother's Maiden Name", pi.mothersMaidenName);

  if (pi.spouseName) {
    y += 4;
    doc.setFontSize(12);
    doc.setFont("helvetica", "bold");
    doc.setTextColor(...HEADER_COLOR);
    doc.text("Spouse / Partner", PAGE_MARGIN, y);
    y += 7;
    doc.setTextColor(30);
    labelValue("Spouse's Name", pi.spouseName);
    labelValue("Spouse's SIN", maskSIN(pi.spouseSin));
    labelValue("Date of Marriage", formatDate(pi.dateOfMarriage));
    labelValue("Spouse's DOB", formatDate(pi.spouseDateOfBirth));
  }

  // ============ SECTION 2: DEBTS ============
  if (data.debts.creditCards.length > 0 || data.debts.linesOfCredit.length > 0) {
    doc.addPage();
    y = PAGE_MARGIN;
    sectionHeader("2. Debts");

    if (data.debts.creditCards.length > 0) {
      doc.setFontSize(12);
      doc.setFont("helvetica", "bold");
      doc.text("Credit Cards", PAGE_MARGIN, y);
      y += 6;

      autoTable(doc, {
        startY: y,
        margin: { left: PAGE_MARGIN, right: PAGE_MARGIN },
        head: [["Issuer", "Card Number", "Interest", "Min. Payment", "Balance"]],
        body: data.debts.creditCards.map((c) => [
          c.issuer,
          maskCardNumber(c.cardNumber),
          c.interestRate,
          c.minimumPayment ? formatCurrency(parseCurrency(c.minimumPayment)) : "",
          c.balanceOwing ? formatCurrency(parseCurrency(c.balanceOwing)) : "",
        ]),
        headStyles: { fillColor: HEADER_COLOR, fontSize: 9 },
        bodyStyles: { fontSize: 9 },
        theme: "grid",
      });

      // eslint-disable-next-line @typescript-eslint/no-explicit-any
      y = (doc as any).lastAutoTable.finalY + 5;
      doc.setFontSize(10);
      doc.setFont("helvetica", "bold");
      doc.text(
        `Total Credit Card Debt: ${formatCurrency(totalCreditCardDebt(data))}`,
        pageWidth - PAGE_MARGIN,
        y,
        { align: "right" }
      );
      y += 10;
    }

    if (data.debts.linesOfCredit.length > 0) {
      checkNewPage(30);
      doc.setFontSize(12);
      doc.setFont("helvetica", "bold");
      doc.text("Lines of Credit", PAGE_MARGIN, y);
      y += 6;

      autoTable(doc, {
        startY: y,
        margin: { left: PAGE_MARGIN, right: PAGE_MARGIN },
        head: [["Lender", "Account Number", "Balance"]],
        body: data.debts.linesOfCredit.map((l) => [
          l.lender,
          l.accountNumber,
          l.balance ? formatCurrency(parseCurrency(l.balance)) : "",
        ]),
        headStyles: { fillColor: HEADER_COLOR, fontSize: 9 },
        bodyStyles: { fontSize: 9 },
        theme: "grid",
      });

      // eslint-disable-next-line @typescript-eslint/no-explicit-any
      y = (doc as any).lastAutoTable.finalY + 5;
      doc.setFontSize(10);
      doc.setFont("helvetica", "bold");
      doc.text(
        `Total Lines of Credit: ${formatCurrency(totalLineOfCreditDebt(data))}`,
        pageWidth - PAGE_MARGIN,
        y,
        { align: "right" }
      );
    }
  }

  // ============ SECTION 3: BANK ACCOUNTS ============
  if (data.bankAccounts.accounts.length > 0) {
    doc.addPage();
    y = PAGE_MARGIN;
    sectionHeader("3. Bank Accounts & Investments");

    autoTable(doc, {
      startY: y,
      margin: { left: PAGE_MARGIN, right: PAGE_MARGIN },
      head: [["Institution", "Type", "Account #", "Rate", "Balance"]],
      body: data.bankAccounts.accounts.map((a) => [
        a.institutionName,
        ACCOUNT_TYPE_LABELS[a.accountType] || a.accountType,
        a.accountNumber,
        a.interestRate,
        a.totalBalance ? formatCurrency(parseCurrency(a.totalBalance)) : "",
      ]),
      headStyles: { fillColor: HEADER_COLOR, fontSize: 9 },
      bodyStyles: { fontSize: 9 },
      theme: "grid",
    });

    // eslint-disable-next-line @typescript-eslint/no-explicit-any
    y = (doc as any).lastAutoTable.finalY + 5;
    doc.setFontSize(11);
    doc.setFont("helvetica", "bold");
    doc.text(
      `Total: ${formatCurrency(totalBankBalances(data))}`,
      pageWidth - PAGE_MARGIN,
      y,
      { align: "right" }
    );
  }

  // ============ SECTION 4: REAL ESTATE ============
  if (data.realEstate.properties.length > 0) {
    doc.addPage();
    y = PAGE_MARGIN;
    sectionHeader("4. Real Estate");

    data.realEstate.properties.forEach((prop, i) => {
      checkNewPage(50);
      doc.setFontSize(12);
      doc.setFont("helvetica", "bold");
      doc.text(`Property ${i + 1}: ${prop.propertyName || "Unnamed"}`, PAGE_MARGIN, y);
      y += 7;
      labelValue("Address", prop.address);
      labelValue("Purchase Date", formatDate(prop.purchaseDate));
      labelValue("Real Estate Agent", prop.realEstateAgent);
      labelValue("Mortgage Lender", prop.mortgageLender);
      labelValue("Property Roll #", prop.propertyRollNumber);
      labelValue("Mortgage Balance", prop.mortgageBalance ? formatCurrency(parseCurrency(prop.mortgageBalance)) : "");
      labelValue("Approx. Value", prop.approximateValue ? formatCurrency(parseCurrency(prop.approximateValue)) : "");
      y += 4;
    });

    doc.setFontSize(11);
    doc.setFont("helvetica", "bold");
    doc.text(
      `Total Property Value: ${formatCurrency(totalRealEstateValue(data))} | Mortgages: ${formatCurrency(totalMortgageBalance(data))}`,
      PAGE_MARGIN,
      y
    );
  }

  // ============ SECTION 5: INSURANCE ============
  const insuranceCategories = [
    { key: "automobile" as const, label: "Automobile" },
    { key: "homeowners" as const, label: "Homeowner's / Renter's" },
    { key: "life" as const, label: "Life Insurance (General)" },
    { key: "termLife" as const, label: "Term Life Insurance" },
    { key: "wholeLife" as const, label: "Whole Life Insurance" },
    { key: "criticalIllness" as const, label: "Critical Illness Insurance" },
    { key: "disability" as const, label: "Disability Insurance" },
    { key: "extendedHealth" as const, label: "Extended Health / Dental" },
    { key: "travel" as const, label: "Travel Insurance" },
    { key: "longTermCare" as const, label: "Long-Term Care" },
    { key: "mortgage" as const, label: "Mortgage Insurance (CMHC)" },
    { key: "pet" as const, label: "Pet Insurance" },
    { key: "other" as const, label: "Other" },
  ];

  const hasInsurance = insuranceCategories.some(
    (c) => data.insurance[c.key].length > 0
  );

  if (hasInsurance) {
    doc.addPage();
    y = PAGE_MARGIN;
    sectionHeader("5. Insurance Plans");

    insuranceCategories.forEach(({ key, label }) => {
      const policies = data.insurance[key];
      if (policies.length === 0) return;

      checkNewPage(25);
      doc.setFontSize(12);
      doc.setFont("helvetica", "bold");
      doc.text(label, PAGE_MARGIN, y);
      y += 6;

      const showBeneficiary = ["life", "termLife", "wholeLife", "criticalIllness"].includes(key);
      const heads = showBeneficiary
        ? [["Provider", "Policy #", "Contact", "Premium", "Beneficiary"]]
        : [["Provider", "Policy #", "Contact", "Premium", "Coverage"]];

      autoTable(doc, {
        startY: y,
        margin: { left: PAGE_MARGIN, right: PAGE_MARGIN },
        head: heads,
        body: policies.map((p) => [
          p.provider,
          p.policyNumber,
          p.contactInfo,
          p.premium ? formatCurrency(parseCurrency(p.premium)) : "",
          showBeneficiary ? (p.beneficiary || "") : p.coverageDetails,
        ]),
        headStyles: { fillColor: HEADER_COLOR, fontSize: 9 },
        bodyStyles: { fontSize: 9 },
        theme: "grid",
      });

      // eslint-disable-next-line @typescript-eslint/no-explicit-any
      y = (doc as any).lastAutoTable.finalY + 10;
    });
  }

  // ============ SECTION 6: INCOME ============
  if (data.income.sources.length > 0) {
    doc.addPage();
    y = PAGE_MARGIN;
    sectionHeader("6. Income Sources");

    autoTable(doc, {
      startY: y,
      margin: { left: PAGE_MARGIN, right: PAGE_MARGIN },
      head: [["Source", "Type", "Payment Day", "Reference #", "Monthly", "Split?"]],
      body: data.income.sources.map((s) => [
        s.companyOrSource,
        INCOME_TYPE_LABELS[s.type] || s.type,
        s.paymentDayOfMonth,
        s.policyReferenceNumber,
        s.monthlyPaymentAmount
          ? formatCurrency(parseCurrency(s.monthlyPaymentAmount))
          : "",
        s.splitWithSpouse === "yes" ? "Yes" : "",
      ]),
      headStyles: { fillColor: HEADER_COLOR, fontSize: 9 },
      bodyStyles: { fontSize: 9 },
      theme: "grid",
    });

    // eslint-disable-next-line @typescript-eslint/no-explicit-any
    y = (doc as any).lastAutoTable.finalY + 5;
    doc.setFontSize(11);
    doc.setFont("helvetica", "bold");
    doc.text(
      `Total Monthly Income: ${formatCurrency(totalMonthlyIncome(data))}`,
      pageWidth - PAGE_MARGIN,
      y,
      { align: "right" }
    );
  }

  // ============ SECTION 7: EXPENSES ============
  // Only include expenses where the user has actually filled in data
  // (not just pre-populated description templates)
  const filledExpenses = data.expenses.expenses.filter(
    (e) => e.companyName.trim() !== "" || e.monthlyAmount.trim() !== ""
  );
  if (filledExpenses.length > 0) {
    doc.addPage();
    y = PAGE_MARGIN;
    sectionHeader("7. Monthly Expenses & Bills");

    autoTable(doc, {
      startY: y,
      margin: { left: PAGE_MARGIN, right: PAGE_MARGIN },
      head: [["Description", "Company", "Payment Type", "Day", "Amount"]],
      body: filledExpenses.map((e) => [
        e.description,
        e.companyName,
        e.paymentType,
        e.paymentDayOfMonth,
        e.monthlyAmount
          ? formatCurrency(parseCurrency(e.monthlyAmount))
          : "",
      ]),
      headStyles: { fillColor: HEADER_COLOR, fontSize: 9 },
      bodyStyles: { fontSize: 9 },
      theme: "grid",
    });

    // eslint-disable-next-line @typescript-eslint/no-explicit-any
    y = (doc as any).lastAutoTable.finalY + 5;
    doc.setFontSize(11);
    doc.setFont("helvetica", "bold");
    doc.text(
      `Total Monthly Expenses: ${formatCurrency(totalMonthlyExpenses(data))}`,
      pageWidth - PAGE_MARGIN,
      y,
      { align: "right" }
    );
  }

  // ============ SECTION 8: IMPORTANT CONTACTS ============
  const ic = data.importantContacts;
  if (hasContactsData(ic)) {
  doc.addPage();
  y = PAGE_MARGIN;
  sectionHeader("8. Important Contacts & Notes");

  if (ic.lawyerName || ic.lawyerContact || ic.accountantName || ic.financialAdvisorName) {
    doc.setFontSize(12);
    doc.setFont("helvetica", "bold");
    doc.text("Legal & Financial", PAGE_MARGIN, y);
    y += 7;
    if (ic.lawyerName || ic.lawyerContact) labelValue("Lawyer", `${ic.lawyerName} — ${ic.lawyerContact}`);
    if (ic.accountantName || ic.accountantContact) labelValue("Accountant", `${ic.accountantName} — ${ic.accountantContact}`);
    if (ic.financialAdvisorName || ic.financialAdvisorContact) labelValue("Financial Advisor", `${ic.financialAdvisorName} — ${ic.financialAdvisorContact}`);
    y += 4;
  }

  if (ic.serviceCanadaNumber || ic.veteransAffairsNumber || ic.unionLocal || ic.pensionAdministrator) {
    checkNewPage(30);
    doc.setFontSize(12);
    doc.setFont("helvetica", "bold");
    doc.text("Government & Pension", PAGE_MARGIN, y);
    y += 7;
    labelValue("Service Canada Ref #", ic.serviceCanadaNumber);
    labelValue("Veterans Affairs #", ic.veteransAffairsNumber);
    labelValue("Union Local / Contact", ic.unionLocal);
    labelValue("Pension Administrator", ic.pensionAdministrator);
    y += 4;
  }

  if (ic.funeralHome || ic.funeralPrePaid) {
    checkNewPage(30);
    doc.setFontSize(12);
    doc.setFont("helvetica", "bold");
    doc.text("Funeral Arrangements", PAGE_MARGIN, y);
    y += 7;
    labelValue("Funeral Home", ic.funeralHome);
    labelValue("Pre-Paid", ic.funeralPrePaid);
    labelValue("Details", ic.funeralDetails);
    y += 4;
  }

  if (ic.executorOfWill || ic.locationOfWill) {
    checkNewPage(30);
    doc.setFontSize(12);
    doc.setFont("helvetica", "bold");
    doc.text("Will & Estate", PAGE_MARGIN, y);
    y += 7;
    labelValue("Executor of Will", ic.executorOfWill);
    labelValue("Location of Will", ic.locationOfWill);
    labelValue("Safety Deposit Box", ic.safetyDepositBoxLocation);
    labelValue("Key Location", ic.safetyDepositBoxKeyLocation);
    y += 4;
  }

  if (ic.otherNotes) {
    checkNewPage(20);
    doc.setFontSize(12);
    doc.setFont("helvetica", "bold");
    doc.text("Other Notes", PAGE_MARGIN, y);
    y += 7;
    doc.setFontSize(10);
    doc.setFont("helvetica", "normal");
    const lines = doc.splitTextToSize(
      ic.otherNotes,
      pageWidth - PAGE_MARGIN * 2
    );
    doc.text(lines, PAGE_MARGIN, y);
  }
  } // end hasContactsData

  // Add footer to all pages
  const totalPages = doc.getNumberOfPages();
  for (let i = 1; i <= totalPages; i++) {
    doc.setPage(i);
    addFooter(i);
  }

  // Download
  const filename = `ReadyRecord_${name.replace(/[^a-zA-Z0-9]/g, "_")}_${new Date().toISOString().split("T")[0]}.pdf`;
  doc.save(filename);
}
